version: '3'

services:
  app:
    build:
      dockerfile: ./Dockerfile
      context: .
    environment:
      DATABASE_URL: postgresql://user:password@database:5432/blog
    ports:
    - '8080:5000'
    depends_on:
      - database
  database:
    image: postgres:12.7-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  pgdata: